print("Hello World!")
print("I am learning Git and GitHub.")
print("Git is tracking my changes.")
print("I am learning Git from VS Code.")
print("Now I understand Git and GitHub.")
print("now i am learning this push method by own without chatgpt help.")
print("This change was made on GitHub.")